=== darkmusic/carbon-rewind-color-theme/themes/_palettes/_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Carbon Rewind Palette",
  "type": "object",
  "required": ["id", "label", "scaffold", "roles"],
  "properties": {
    "id": { "type": "string", "pattern": "^[a-z0-9-]+$" },
    "label": { "type": "string" },
    "scaffold": { "enum": ["maya", "base", "pure", "winter"] },
    "extends": { "type": "string" },
    "publish": { "type": "boolean", "default": true },
    "roles": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "pattern": "^#[0-9a-fA-F]{3,8}$"
      }
    },
    "replacements": {
      "type": "object",
      "additionalProperties": { "type": "string" }
    }
  },
  "additionalProperties": false
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/maya-black.json
{
  "id": "maya-black",
  "label": "Carbon Rewind Color Theme - Maya Black",
  "scaffold": "maya",
  "roles": {
    "c_000000": "#000000",
    "c_000205": "#000205",
    "c_06090d": "#06090d",
    "c_11151c": "#11151c",
    "c_131721": "#111620",
    "c_39bae6": "#39bae6",
    "c_409fff": "#409fff",
    "c_475266": "#475266",
    "c_53bdfa": "#53bdfa",
    "c_565b66": "#565b66",
    "c_59c2ff": "#59c2ff",
    "c_5f4c72": "#5f4c72",
    "c_686868": "#686868",
    "c_6c5980": "#6c5980",
    "c_6c7380": "#6c7380",
    "c_73b8ff": "#73b8ff",
    "c_7fd962": "#7fd962",
    "c_90e1c6": "#90e1c6",
    "c_95e6cb": "#95e6cb",
    "c_a28bc0": "#a28bc0",
    "c_aad94c": "#aad94c",
    "c_acb6bf": "#9aa3ac",
    "c_bfbdb6": "#bfbdb6",
    "c_c594c5": "#c594c5",
    "c_c7c7c7": "#c7c7c7",
    "c_cda1fa": "#cda1fa",
    "c_d2a6ff": "#d2a6ff",
    "c_d95757": "#d95757",
    "c_e06c75": "#e06c75",
    "c_e1af4b": "#e1af4b",
    "c_e6b450": "#e6b450",
    "c_e6b673": "#e6b673",
    "c_ea6c73": "#ea6c73",
    "c_f07178": "#f07178",
    "c_f26d78": "#f26d78",
    "c_f29668": "#f29668",
    "c_f7ecb5": "#f7ecb5",
    "c_f9af4f": "#f9af4f",
    "c_ff8f40": "#ff8f40",
    "c_ffb454": "#ffb454",
    "c_ffffff": "#ffffff",
    "c_0b0e14": "#010308"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/_baseline/color.json
{
  "id": "color",
  "label": "Carbon Rewind Color Theme",
  "scaffold": "base",
  "roles": {
    "c_000000": "#000000",
    "c_001111": "#001111",
    "c_00809b": "#00809b",
    "c_010b14": "#010b14",
    "c_011627": "#011627",
    "c_020202": "#020202",
    "c_022846": "#022846",
    "c_03648a": "#03648a",
    "c_06202c": "#06202c",
    "c_072243": "#072243",
    "c_0b0e12": "#0b0e12",
    "c_0d1014": "#0d1014",
    "c_0f1318": "#0f1318",
    "c_10161c": "#10161c",
    "c_103362": "#103362",
    "c_121212": "#121212",
    "c_151d25": "#151d25",
    "c_181a1f": "#181a1f",
    "c_1d1f23": "#1d1f23",
    "c_202020": "#202020",
    "c_20282d": "#20282d",
    "c_212025": "#212025",
    "c_219fd5": "#219fd5",
    "c_262a39": "#262a39",
    "c_2c313a": "#2c313a",
    "c_2e3250": "#2e3250",
    "c_303030": "#303030",
    "c_314365": "#314365",
    "c_383e4a": "#383e4a",
    "c_3b4048": "#3b4048",
    "c_3e4451": "#3e4451",
    "c_407040": "#407040",
    "c_4373c2": "#4373c2",
    "c_484848": "#484848",
    "c_484a50": "#484a50",
    "c_495162": "#495162",
    "c_4c0769": "#4c0769",
    "c_4e5666": "#4e5666",
    "c_4ed6d6": "#4ed6d6",
    "c_528bff": "#528bff",
    "c_56b6c2": "#56b6c2",
    "c_5a6375": "#5a6375",
    "c_5abeb0": "#5abeb0",
    "c_5c6370": "#5c6370",
    "c_5f7e97": "#5f7e97",
    "c_61afef": "#61afef",
    "c_6796e6": "#6796e6",
    "c_696969": "#696969",
    "c_697098": "#697098",
    "c_6b717d": "#6b717d",
    "c_704040": "#704040",
    "c_707040": "#707040",
    "c_747d91": "#747d91",
    "c_75715e": "#75715e",
    "c_7799bb": "#7799bb",
    "c_7e57c2": "#7e57c2",
    "c_80cbc4": "#80cbc4",
    "c_8282c7": "#8282c7",
    "c_975f94": "#975f94",
    "c_98c379": "#98c379",
    "c_98c8ed": "#98c8ed",
    "c_9da5b4": "#9da5b4",
    "c_abb2bf": "#abb2bf",
    "c_addb67": "#addb67",
    "c_b267e6": "#b267e6",
    "c_b6a0a0": "#b6a0a0",
    "c_bbbbbb": "#bbbbbb",
    "c_c5c5c5": "#c5c5c5",
    "c_c678dd": "#c678dd",
    "c_c792ea": "#c792ea",
    "c_cd9731": "#cd9731",
    "c_cecece": "#cecece",
    "c_d19a66": "#d19a66",
    "c_d2dee7": "#d2dee7",
    "c_d6deeb": "#d6deeb",
    "c_d7dae0": "#d7dae0",
    "c_e06c75": "#e06c75",
    "c_e5c07b": "#e5c07b",
    "c_ef5350": "#ef5350",
    "c_f44747": "#f44747",
    "c_f7ecb5": "#f7ecb5",
    "c_f8f8f0": "#f8f8f0",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/dusk.json
{
  "id": "dusk",
  "label": "Carbon Rewind Color Theme - Dusk",
  "scaffold": "maya",
  "roles": {
    "c_000000": "#000000",
    "c_0b0e14": "#0e0a14",
    "c_0d1017": "#120d18",
    "c_0f131a": "#110c17",
    "c_11151c": "#1a1424",
    "c_131721": "#15101e",
    "c_39bae6": "#c4a8ff",
    "c_409fff": "#9d7cff4d",
    "c_475266": "#4a3a60",
    "c_53bdfa": "#9d7cff",
    "c_565b66": "#6a6080",
    "c_59c2ff": "#a78bfa",
    "c_5f4c72": "#5a4080",
    "c_686868": "#686868",
    "c_6c5980": "#6b5090",
    "c_6c7380": "#7a7090",
    "c_73b8ff": "#9d7cff",
    "c_7fd962": "#b794f6",
    "c_90e1c6": "#d8b4fe",
    "c_95e6cb": "#d8b4fe",
    "c_a28bc0": "#d8b4fe",
    "c_aad94c": "#c4a8ff",
    "c_acb6bf": "#7a7090",
    "c_bfbdb6": "#bfbdb6",
    "c_c594c5": "#c4a8ff",
    "c_c7c7c7": "#c7c7c7",
    "c_cda1fa": "#d8b4fe",
    "c_d2a6ff": "#ffb4e6",
    "c_d95757": "#d95757",
    "c_e06c75": "#e2b0ff",
    "c_e1af4b": "#8f6ef0",
    "c_e6b450": "#9d7cff",
    "c_e6b673": "#d8b4fe",
    "c_ea6c73": "#ea6c73",
    "c_f07178": "#ffb4e6",
    "c_f26d78": "#f26d78",
    "c_f29668": "#c4a8ff",
    "c_f7ecb5": "#e9d5ff",
    "c_f9af4f": "#e2b0ff",
    "c_ff8f40": "#b794f6",
    "c_ffb454": "#e2b0ff",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/moss.json
{
  "id": "moss",
  "label": "Carbon Rewind Color Theme - Moss",
  "scaffold": "maya",
  "roles": {
    "c_000000": "#000000",
    "c_0b0e14": "#0a0f0c",
    "c_0d1017": "#0e1511",
    "c_0f131a": "#0c1210",
    "c_11151c": "#152018",
    "c_131721": "#101812",
    "c_39bae6": "#7ec699",
    "c_409fff": "#5dbd734d",
    "c_475266": "#3a5540",
    "c_53bdfa": "#5dbd73",
    "c_565b66": "#5a7560",
    "c_59c2ff": "#6dbf8a",
    "c_5f4c72": "#3a5540",
    "c_686868": "#686868",
    "c_6c5980": "#4a6850",
    "c_6c7380": "#6b8f71",
    "c_73b8ff": "#5dbd73",
    "c_7fd962": "#7fd962",
    "c_90e1c6": "#9ad4a8",
    "c_95e6cb": "#9ad4a8",
    "c_a28bc0": "#8ec9a0",
    "c_aad94c": "#a8e6a1",
    "c_acb6bf": "#6b8f71",
    "c_bfbdb6": "#bfbdb6",
    "c_c594c5": "#7ec699",
    "c_c7c7c7": "#c7c7c7",
    "c_cda1fa": "#a8e6a1",
    "c_d2a6ff": "#c9e894",
    "c_d95757": "#d95757",
    "c_e06c75": "#6ec985",
    "c_e1af4b": "#52b068",
    "c_e6b450": "#5dbd73",
    "c_e6b673": "#a8e6a1",
    "c_ea6c73": "#ea6c73",
    "c_f07178": "#8fd4a0",
    "c_f26d78": "#e07070",
    "c_f29668": "#7ec699",
    "c_f7ecb5": "#c9e894",
    "c_f9af4f": "#c9e894",
    "c_ff8f40": "#6ec985",
    "c_ffb454": "#a8e6a1",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/maya.json
{
  "id": "maya",
  "label": "Carbon Rewind Color Theme - Maya",
  "scaffold": "maya",
  "roles": {
    "c_000000": "#000000",
    "c_0b0e14": "#0b0e14",
    "c_0d1017": "#0d1017",
    "c_0f131a": "#0f131a",
    "c_11151c": "#11151c",
    "c_131721": "#111620",
    "c_39bae6": "#39bae6",
    "c_409fff": "#409fff",
    "c_475266": "#475266",
    "c_53bdfa": "#53bdfa",
    "c_565b66": "#565b66",
    "c_59c2ff": "#59c2ff",
    "c_5f4c72": "#5f4c72",
    "c_686868": "#686868",
    "c_6c5980": "#6c5980",
    "c_6c7380": "#6c7380",
    "c_73b8ff": "#73b8ff",
    "c_7fd962": "#7fd962",
    "c_90e1c6": "#90e1c6",
    "c_95e6cb": "#95e6cb",
    "c_a28bc0": "#a28bc0",
    "c_aad94c": "#aad94c",
    "c_acb6bf": "#9aa3ac",
    "c_bfbdb6": "#bfbdb6",
    "c_c594c5": "#c594c5",
    "c_c7c7c7": "#c7c7c7",
    "c_cda1fa": "#cda1fa",
    "c_d2a6ff": "#d2a6ff",
    "c_d95757": "#d95757",
    "c_e06c75": "#e06c75",
    "c_e1af4b": "#e1af4b",
    "c_e6b450": "#e6b450",
    "c_e6b673": "#e6b673",
    "c_ea6c73": "#ea6c73",
    "c_f07178": "#f07178",
    "c_f26d78": "#f26d78",
    "c_f29668": "#f29668",
    "c_f7ecb5": "#f7ecb5",
    "c_f9af4f": "#f9af4f",
    "c_ff8f40": "#ff8f40",
    "c_ffb454": "#ffb454",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/obsidian.json
{
  "id": "obsidian",
  "label": "Carbon Rewind Color Theme - Obsidian",
  "scaffold": "maya",
  "roles": {
    "c_000000": "#000000",
    "c_0b0e14": "#101418",
    "c_0d1017": "#141920",
    "c_0f131a": "#12161c",
    "c_11151c": "#1a2028",
    "c_131721": "#161b22",
    "c_39bae6": "#8fd4c8",
    "c_409fff": "#56c2c24d",
    "c_475266": "#3a4550",
    "c_53bdfa": "#56c2c2",
    "c_565b66": "#8899aa",
    "c_59c2ff": "#56c2c2",
    "c_5f4c72": "#3a5050",
    "c_686868": "#686868",
    "c_6c5980": "#4a6060",
    "c_6c7380": "#708090",
    "c_73b8ff": "#56c2c2",
    "c_7fd962": "#7fd962",
    "c_90e1c6": "#8fd4c8",
    "c_95e6cb": "#8fd4c8",
    "c_a28bc0": "#a0b8c0",
    "c_aad94c": "#8fd4c8",
    "c_acb6bf": "#708090",
    "c_bfbdb6": "#b0bec5",
    "c_c594c5": "#8fd4c8",
    "c_c7c7c7": "#c7c7c7",
    "c_cda1fa": "#a0c8c0",
    "c_d2a6ff": "#d4a843",
    "c_d95757": "#d95757",
    "c_e06c75": "#8fd4c8",
    "c_e1af4b": "#4db8b8",
    "c_e6b450": "#56c2c2",
    "c_e6b673": "#d4a843",
    "c_ea6c73": "#ea6c73",
    "c_f07178": "#a0c8c0",
    "c_f26d78": "#e07070",
    "c_f29668": "#8fd4c8",
    "c_f7ecb5": "#d4a843",
    "c_f9af4f": "#d4a843",
    "c_ff8f40": "#6ec9c9",
    "c_ffb454": "#d4a843",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/_baseline/winter.json
{
  "id": "winter",
  "label": "Carbon Rewind Color Theme - Winter",
  "scaffold": "winter",
  "roles": {
    "c_000000": "#000000",
    "c_000a11": "#000a11",
    "c_001111": "#001111",
    "c_00bff9": "#00bff9",
    "c_010e1a": "#010e1a",
    "c_011627": "#011627",
    "c_022846": "#022846",
    "c_03648a": "#03648a",
    "c_060d1f": "#060d1f",
    "c_071021": "#071021",
    "c_084d81": "#084d81",
    "c_0b253a": "#0b253a",
    "c_0b2942": "#0b2942",
    "c_0c4994": "#0c4994",
    "c_0e293f": "#0e293f",
    "c_0e2c45": "#0e2c45",
    "c_103362": "#103362",
    "c_112233": "#112233",
    "c_122d42": "#122d42",
    "c_151d25": "#151d25",
    "c_181a1f": "#181a1f",
    "c_219fd5": "#219fd5",
    "c_262a39": "#262a39",
    "c_2b2f40": "#2b2f40",
    "c_2c3043": "#2c3043",
    "c_2e3250": "#2e3250",
    "c_303030": "#303030",
    "c_3b3a32": "#3b3a32",
    "c_4373c2": "#4373c2",
    "c_4fb4d8": "#4fb4d8",
    "c_57cdff": "#57cdff",
    "c_5abeb0": "#5abeb0",
    "c_5f7e97": "#5f7e97",
    "c_697098": "#697098",
    "c_6bff81": "#6bff81",
    "c_6dbdfa": "#6dbdfa",
    "c_7799bb": "#7799bb",
    "c_78bd65": "#78bd65",
    "c_7e57c2": "#7e57c2",
    "c_7fdbca": "#7fdbca",
    "c_80cbc4": "#80cbc4",
    "c_82aaff": "#82aaff",
    "c_87aff4": "#87aff4",
    "c_8dec95": "#8dec95",
    "c_91dacd": "#91dacd",
    "c_92b6f4": "#92b6f4",
    "c_975f94": "#975f94",
    "c_98c8ed": "#98c8ed",
    "c_999999": "#999999",
    "c_99b76d": "#99b76d",
    "c_99d0f7": "#99d0f7",
    "c_a170c6": "#a170c6",
    "c_a1bde6": "#a1bde6",
    "c_a4ceee": "#a4ceee",
    "c_a7dbf7": "#a7dbf7",
    "c_addb67": "#addb67",
    "c_b15a91": "#b15a91",
    "c_bce7ff": "#bce7ff",
    "c_bcf0c0": "#bcf0c0",
    "c_c63ed3": "#c63ed3",
    "c_c792ea": "#c792ea",
    "c_cbcdd2": "#cbcdd2",
    "c_cecece": "#cecece",
    "c_d29ffc": "#d29ffc",
    "c_d2dee7": "#d2dee7",
    "c_d3eed6": "#d3eed6",
    "c_d6deeb": "#d6deeb",
    "c_d7dbe0": "#d7dbe0",
    "c_e0aff5": "#e0aff5",
    "c_ec9cd2": "#ec9cd2",
    "c_ece7cd": "#ece7cd",
    "c_eeefff": "#eeefff",
    "c_eeffff": "#eeffff",
    "c_ef5350": "#ef5350",
    "c_f29fd8": "#f29fd8",
    "c_f3b8c2": "#f3b8c2",
    "c_f7ecb5": "#f7ecb5",
    "c_ffca28": "#ffca28",
    "c_ffffff": "#ffffff"
  }
}

=== darkmusic/carbon-rewind-color-theme/themes/_palettes/_baseline/pure.json
{
  "id": "pure",
  "label": "Carbon Rewind Color Theme - Pure",
  "scaffold": "pure",
  "roles": {
    "c_000000": "#000000",
    "c_07d258": "#07d258",
    "c_0b0c0e": "#0b0c0e",
    "c_121212": "#121212",
    "c_141519": "#141519",
    "c_1b1d22": "#1b1d22",
    "c_20bcff": "#20bcff",
    "c_24966e": "#24966e",
    "c_282c33": "#282c33",
    "c_2f7ecd": "#2f7ecd",
    "c_3398db": "#3398db",
    "c_370067": "#370067",
    "c_37ae6f": "#37ae6f",
    "c_4c5767": "#4c5767",
    "c_56b6c2": "#56b6c2",
    "c_5c6370": "#5c6370",
    "c_61afef": "#61afef",
    "c_627e99": "#627e99",
    "c_6796e6": "#6796e6",
    "c_696969": "#696969",
    "c_75715e": "#75715e",
    "c_8b56bf": "#8b56bf",
    "c_98c379": "#98c379",
    "c_9aa1ac": "#9aa1ac",
    "c_abb2bf": "#abb2bf",
    "c_b267e6": "#b267e6",
    "c_bbbbbb": "#bbbbbb",
    "c_bd1c98": "#bd1c98",
    "c_bf568b": "#bf568b",
    "c_bf8b56": "#bf8b56",
    "c_bfa656": "#bfa656",
    "c_c13838": "#c13838",
    "c_c678dd": "#c678dd",
    "c_cbd6e2": "#cbd6e2",
    "c_cd9731": "#cd9731",
    "c_d19a66": "#d19a66",
    "c_d26d32": "#d26d32",
    "c_d39e17": "#d39e17",
    "c_e06c75": "#e06c75",
    "c_e3b625": "#e3b625",
    "c_e5c07b": "#e5c07b",
    "c_e6d7f4": "#e6d7f4",
    "c_f44747": "#f44747",
    "c_f8f8f0": "#f8f8f0",
    "c_ffffff": "#ffffff"
  }
}
